### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by danhab05** [Grunnpi/EcoleDirecte#1]
```
Traceback (most recent call last):
  File "EcoleDirecte.py", line 182, in <module>
    creds = ServiceAccountCredentials.from_json_keyfile_name(str(args.cred), scope)
  File "C:\Users\danha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oauth2client\service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by Grunnpi** [comment]
Google Drive usage is now mandatory
I've updated readme and credential parsing to avoid error raising without explanation
